//Home page
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS"
export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST"
export const CATEGORIES_ERROR = "CATEGORIES_ERROR"

// Products Page
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_ERROR = "PRODUCT_ERROR"

// AddToCart Page
export const CART_SUCCESS = "CART_SUCCESS"
export const CART_REQUEST = "CART_REQUEST"
export const CART_ERROR = "CART_ERROR"

// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";